package com.finalertpro.model;

public enum AlertType {
    MARKET_ORDER_EXECUTED,
    LIMIT_ORDER_EXECUTED,
    PRICE_SWING,
    VOLUME_ANOMALY,
    LIQUIDITY_WARNING,
    VOLATILITY_ALERT,
    INSTITUTIONAL_MOVEMENT,
    BLOCK_TRADE_OPPORTUNITY,
    ARBITRAGE_OPPORTUNITY,
    REGULATORY_ALERT
}
